// CrewCall — sample data. Replace with a real backend/API when ready.
window.CREW_DATA = {
  roles: [
    'Filmer / Videographer',
    'Video Editor',
    'Scriptwriter',
    'Thumbnail Designer',
    'Producer',
    'Sound / Audio',
    'Motion Graphics',
    'Channel Strategist',
  ],

  platforms: ['YouTube', 'TikTok', 'Instagram', 'Twitch', 'Podcast'],

  crew: [
    { id: 1, name: 'Maya Okafor', role: 'Filmer / Videographer', location: 'Austin, TX', remote: false, onsite: true, rate: 650, rating: 4.9, projects: 84, available: true,
      platforms: ['YouTube', 'Instagram'], skills: ['Sony FX3', 'Run-and-gun', 'Travel vlogs', 'Drone (Part 107)'],
      credits: ['@roamwithrae', '@foodtruckfridays'], bio: 'Shoots fast-moving vlog and travel content. Can fly out with a one-bag kit and hand off organized footage same day.' },
    { id: 2, name: 'Leo Brandt', role: 'Video Editor', location: 'Berlin, DE', remote: true, onsite: false, rate: 400, rating: 4.8, projects: 212, available: true,
      platforms: ['YouTube'], skills: ['Premiere Pro', 'Retention editing', 'Sound design', 'Long-form docs'],
      credits: ['@techteardown', '@historyunboxed'], bio: 'Long-form editor focused on retention curves. 20–40 minute documentary-style videos are my specialty.' },
    { id: 3, name: 'Priya Raman', role: 'Scriptwriter', location: 'Toronto, CA', remote: true, onsite: false, rate: 350, rating: 5.0, projects: 131, available: false,
      platforms: ['YouTube', 'Podcast'], skills: ['Hooks', 'Story structure', 'Research', 'Explainers'],
      credits: ['@scienceinfive', '@moneymadeplain'], bio: 'I write explainer and essay scripts that hold attention past the first 30 seconds. Research included.' },
    { id: 4, name: 'Jordan Reyes', role: 'Thumbnail Designer', location: 'Manila, PH', remote: true, onsite: false, rate: 150, rating: 4.7, projects: 540, available: true,
      platforms: ['YouTube'], skills: ['Photoshop', 'A/B testing', 'Face cutouts', 'Gaming'],
      credits: ['@speedrunsaturday', '@builderbros'], bio: 'Thumbnails built for CTR. Every order includes two variants for YouTube\'s Test & Compare.' },
    { id: 5, name: 'Sam Whitfield', role: 'Filmer / Videographer', location: 'Los Angeles, CA', remote: false, onsite: true, rate: 900, rating: 4.9, projects: 67, available: true,
      platforms: ['YouTube', 'TikTok'], skills: ['Multi-cam', 'Challenge videos', 'Lighting', 'RED Komodo'],
      credits: ['@stuntsquad', '@dailyprank'], bio: 'Big-set challenge and stunt video shooter. Bring me in with a second camera op for multi-cam days.' },
    { id: 6, name: 'Ana Costa', role: 'Video Editor', location: 'Lisbon, PT', remote: true, onsite: false, rate: 250, rating: 4.8, projects: 390, available: true,
      platforms: ['TikTok', 'Instagram', 'YouTube'], skills: ['Shorts / Reels', 'Captions', 'CapCut', 'Trend edits'],
      credits: ['@glowupdaily', '@minutemeals'], bio: 'Vertical-first editor. I can turn one long video into 10 shorts with captions in 48 hours.' },
    { id: 7, name: 'Marcus Lee', role: 'Producer', location: 'New York, NY', remote: true, onsite: true, rate: 800, rating: 4.9, projects: 45, available: false,
      platforms: ['YouTube', 'Podcast'], skills: ['Scheduling', 'Budgets', 'Brand deals', 'Crew hiring'],
      credits: ['@thecitytable', '@startupstories'], bio: 'I run the production side so you can stay on camera: calendars, crews, locations, sponsor deliverables.' },
    { id: 8, name: 'Hana Sato', role: 'Motion Graphics', location: 'Tokyo, JP', remote: true, onsite: false, rate: 500, rating: 4.9, projects: 98, available: true,
      platforms: ['YouTube'], skills: ['After Effects', 'Map animations', 'Data viz', 'Intros'],
      credits: ['@geopolitix', '@chartedhistory'], bio: 'Animated maps, charts and infographics for educational channels.' },
    { id: 9, name: 'Diego Morales', role: 'Sound / Audio', location: 'Mexico City, MX', remote: true, onsite: true, rate: 300, rating: 4.6, projects: 150, available: true,
      platforms: ['Podcast', 'YouTube', 'Twitch'], skills: ['Mixing', 'Noise cleanup', 'Boom op', 'Stream audio setup'],
      credits: ['@latenightpod', '@coffeeandcode'], bio: 'Podcast mixing, dialogue cleanup, and on-set boom work. I\'ll also fix your stream audio chain.' },
    { id: 10, name: 'Chloe Park', role: 'Channel Strategist', location: 'Seoul, KR', remote: true, onsite: false, rate: 700, rating: 5.0, projects: 38, available: true,
      platforms: ['YouTube', 'TikTok'], skills: ['Packaging', 'Analytics', 'Title testing', 'Content calendars'],
      credits: ['@k-beautylab', '@studywithjin'], bio: 'Packaging and analytics consultant. I audit your last 30 uploads and hand you a plan.' },
    { id: 11, name: 'Ethan Brooks', role: 'Scriptwriter', location: 'London, UK', remote: true, onsite: false, rate: 450, rating: 4.8, projects: 76, available: true,
      platforms: ['YouTube'], skills: ['Comedy', 'Sketches', 'Video essays', 'Punch-ups'],
      credits: ['@sketchbritain', '@filmfrenzy'], bio: 'Comedy and video-essay writer. Available for full scripts or punch-up passes on your drafts.' },
    { id: 12, name: 'Nia Johnson', role: 'Filmer / Videographer', location: 'Atlanta, GA', remote: false, onsite: true, rate: 500, rating: 4.7, projects: 59, available: false,
      platforms: ['YouTube', 'Instagram', 'TikTok'], skills: ['Fitness', 'Gimbal', 'Canon C70', 'Vertical + horizontal'],
      credits: ['@liftwithlena', '@atlfoodie'], bio: 'Fitness and lifestyle shooter. I frame for vertical and horizontal at the same time so nothing gets wasted.' },
    { id: 13, name: 'Tomás Silva', role: 'Thumbnail Designer', location: 'São Paulo, BR', remote: true, onsite: false, rate: 200, rating: 4.9, projects: 310, available: true,
      platforms: ['YouTube'], skills: ['3D renders', 'Tech', 'Illustration', 'Photoshop'],
      credits: ['@gadgetgrid', '@pcbuilderpro'], bio: 'Clean, bold tech thumbnails, with 3D product renders when the product shot is weak.' },
    { id: 14, name: 'Rachel Kim', role: 'Video Editor', location: 'Vancouver, CA', remote: true, onsite: false, rate: 550, rating: 5.0, projects: 120, available: false,
      platforms: ['YouTube', 'Twitch'], skills: ['DaVinci Resolve', 'Stream highlights', 'Color', 'Gaming'],
      credits: ['@pixelqueen', '@raidnight'], bio: 'Turns 6-hour streams into tight 15-minute highlight videos. Color grading in Resolve.' },
  ],

  jobs: [
    { title: 'Weekly vlog editor (15–20 min)', role: 'Video Editor', budget: '$350 / video', creator: '@vanlifevera', location: 'Remote', posted: '2d ago' },
    { title: 'Filmer for 3-day food tour shoot', role: 'Filmer / Videographer', budget: '$700 / day', creator: '@eatthestreet', location: 'Chicago, IL', posted: '4d ago' },
    { title: 'Scriptwriter for true-crime series', role: 'Scriptwriter', budget: '$500 / script', creator: '@caseclosedpod', location: 'Remote', posted: '1w ago' },
    { title: 'Thumbnail designer, 3/week', role: 'Thumbnail Designer', budget: '$120 / thumbnail', creator: '@budgetbuilds', location: 'Remote', posted: '1w ago' },
  ],
};
